version: '3'

services:
  proxy:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2

  app1:
    build: ./app1
    ports:
      - "8000:80"

  app2:
    build: ./app2
    ports:
      - "8001:80"